import { GoogleGenAI, Type } from '@google/genai';


export class AIService {
    private ai = new GoogleGenAI({});

    async generateEmbedding(text: string, taskType: string = 'RETRIEVAL_QUERY'): Promise<number[]> {
        const response = await this.ai.models.embedContent({
            model: 'gemini-embedding-001',
            contents: text,
            config: { taskType: taskType, outputDimensionality: 768 }
        });
        return (response as any).embeddings[0].values;
    }

    async analyzeIntentAndExpand(query: string): Promise<{ requiresSearch: boolean, expandedQuery: string }> {
        const prompt = `You are the intent classifier for an AI Second Brain app.
        Your goal is to decide if the user's query requires searching the vector database.
        
        Rule 1 - DO NOT SEARCH (requiresSearch: false):
        If the query is purely conversational, greeting, or filler (e.g. "hi", "how are you", "thanks", ".") and contains NO subject matter.
        
        Rule 2 - DO SEARCH (requiresSearch: true):
        If the query asks for ANY topic, knowledge, facts, OR if the user inquires about the contents of their notes (e.g. "what do you know", "show my notes"). Any query that expects an informative response requires a search.
        
        For Rule 2, extract the core topic and expand it into a "cloud of meanings" (keywords, synonyms). If the query is just a general inquiry about their notes, use general expansion terms like "notes, memory, saved data, knowledge base".
        
        Return ONLY valid JSON: {"requiresSearch": boolean, "expandedQuery": "keyword1, keyword2..."}
        
        User query: "${query}"`;

        try {
            const response = await this.ai.models.generateContent({
                model: 'gemini-2.5-flash',
                contents: [{ role: 'user', parts: [{ text: prompt }] }],
                config: {
                    responseMimeType: 'application/json',
                    temperature: 0.1,
                }
            });

            const parsed = JSON.parse(response.text || "{}");
            return {
                requiresSearch: !!parsed.requiresSearch,
                expandedQuery: parsed.expandedQuery || ""
            };
        } catch (e) {
            console.error("Failed to analyze intent:", e);
            return { requiresSearch: false, expandedQuery: "" };
        }
    }

    async generateAnswer(question: string, contextNotes: string[], history: { role: string, content: string }[] = []): Promise<{ text: string, newNoteData?: any }> {
        const contextText = contextNotes.length > 0 ? contextNotes.join('\n\n---\n\n') : "No information in the knowledge base";
        const saveNoteTool = {
            functionDeclarations: [
                {
                    name: 'saveNote',
                    description: 'Saves new useful information to the note database. Call this function ONLY if the user ASKS TO SAVE a recipe, generate an article, or asks to remember something important forever.',
                    parameters: {
                        type: Type.OBJECT,
                        properties: {
                            messageToUser: {
                                type: Type.STRING,
                                description: 'A very short, friendly message confirming to the user that the note was successfully saved. MUST be in the same language the user is speaking.'
                            },
                            title: {
                                type: Type.STRING,
                                description: 'Short note title (up to 30 characters)'
                            },
                            content: {
                                type: Type.STRING,
                                description: 'Full text of the note, generated by you, preferably formatted in Markdown'
                            },
                            tags: {
                                type: Type.ARRAY,
                                items: { type: Type.STRING },
                                description: 'List of tags for search (e.g. ["recipes", "code"]'
                            }
                        },
                        required: ['messageToUser', 'title', 'content', 'tags']
                    }
                }
            ]
        };

        const systemInstuction = `You are an advanced AI assistant in the "AI Second Brain" application. 
            Your goal is to provide helpful, concise, and CLEAN responses.
            
            Use this decision-making algorithm:
            1. DIRECT COMMANDS HAVE PRIORITY: If the user explicitly asks you to generate/find new information AND save it (e.g., "Find a recipe and save it"), skip all preliminary steps! Generate the answer immediately and silently invoke the save tool.
            2. CONTEXT CHECK: For all other questions, RIGOROUSLY analyze the provided CONTEXT first. If the information exists in the context (even if not an exact match), PROVIDE IT. Do not claim you don't have it if there's any related info.
            3. CLEAN TEXT RULE: Minimize Markdown usage. Use simple bullet points for lists. DO NOT use bolding (**text**) for headers or key terms in personal notes unless absolutely necessary for clarity. Prefer clean, plain text for a minimalist look.
            4. CLARIFICATION: If the user provides a scattered or broad term (e.g. "food"), you CAN ask an interactive clarifying question ("Did you want search results from your notes, or a brand new recipe to save?").
            5. MISSING INFORMATION: If the context definitely lacks the answer, politely offer to use your own knowledge and ask if they'd like to save the result.
            
            CRITICAL SAFETY RULE: NEVER mention the names of internal tools (like saveNote). Act organically.
            Always reply in the language the user speaks to you in.`;

        const formattedHistory = history.map(msg => ({
            role: msg.role === 'user' ? 'user' : 'model',
            parts: [{ text: msg.content }]
        }));

        const currentMessage = {
            role: 'user',
            parts: [{ text: `Context: ${contextText}\n\nQuestion: ${question}` }]
        };

        const response = await this.ai.models.generateContent({
            model: 'gemini-1.5-flash',
            contents: [...formattedHistory, currentMessage],
            config: {
                systemInstruction: systemInstuction,
                tools: [saveNoteTool]
            }
        });

        if (response.functionCalls && response.functionCalls.length > 0) {
            const call = response.functionCalls[0];
            if (call?.name === 'saveNote') {
                const args = call.args as any;
                return {
                    text: args.messageToUser || 'Note saved!',
                    newNoteData: {
                        title: args.title,
                        content: args.content,
                        tags: args.tags
                    }
                }
            }
        }
        return {
            text: response.text || 'Error in response',

        }
    }
}